<?php

/**
 * @file
 * Module adds a guestbook to your site.
 */

/**
 * Implements hook_theme().
 */
function pablo_theme($existing, $type, $theme, $path) {
  return [
    // Default template for a pablo module.
    'pablo_template' => [
      'variables' => [
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function pablo_entity_type_alter(array &$entity_types) {
  $feedback = &$entity_types['feedback'];
  $feedback->setFormClass('feedback_form', 'Drupal\pablo\Form\FeedbackForm');
}
